image: openjdk7
script:
  - ./gradlew assemble
  - ./gradlew check -x integTest
  - ./gradlew publishToMavenLocal  # this is needed for testing the example projects
  - ./gradlew integTest
notify:
  email:
    recipients:
      - {{notifEmail}}
